import { uniqueId } from 'lodash';

import {
  IconPoint,
  IconAlertCircle,
  IconNotes,
  IconCalendar,
  IconMail,
  IconTicket,
  IconEdit,
  IconApps,
  IconFileDescription,
  IconFileDots,
  IconFiles,
  IconBorderAll,
  IconBorderHorizontal,
  IconBorderInner,
  IconBorderVertical,
  IconBorderTop,
  IconPackage,
  IconMessage2,
  IconChartLine,
  IconChartArcs,
  IconChartCandle,
  IconChartArea,
  IconChartDots,
  IconChartDonut3,
  IconChartRadar,
  IconLogin,
  IconUserPlus,
  IconRotate,
  IconShoppingCart,
  IconAperture,
  IconSettings,
  IconUsers,
  IconZoomCode,
  IconBoxAlignBottom,
  IconBoxAlignLeft,
  IconBorderStyle2,
  IconAppWindow,
  IconNotebook,
  IconChartHistogram,
  IconChartPie2,
  IconChartScatter,
  IconChartPpf,
  IconChartArcs3,
  IconCategory,
  IconTags,
  IconBuildingWarehouse,
  IconAdjustmentsHorizontal,
  IconFileInvoice,
  IconTrademark,
  IconDiscount2,
  IconStars,
  IconCrown,
  IconKey,
  IconAddressBook,
  IconIdBadge2,
  IconBuildingStore,
  IconBrandCodesandbox,
  IconWorldMinus,
  IconLanguage,
  IconTarget,
  IconCreditCard,
  IconTruck,
} from '@tabler/icons-react';

const Menuitems = [
  {
    navlabel: true,
    subheader: 'Home',
  },

  {
    id: uniqueId(),
    title: 'Dashboard',
    icon: IconAperture,
    href: '/dashboard',
    chip: 'New',
    chipColor: 'secondary',
  },
  {
    id: uniqueId(),
    title: 'Frontend pages',
    icon: IconAppWindow,
    href: '/frontend-pages/',
    children: [
      {
        id: uniqueId(),
        title: 'Homepage',
        icon: IconPoint,
        href: '/frontend-pages/homepage',
      },
      {
        id: uniqueId(),
        title: 'About Us',
        icon: IconPoint,
        href: '/frontend-pages/about',
      },
      {
        id: uniqueId(),
        title: 'Contact Us',
        icon: IconPoint,
        href: '/frontend-pages/contact',
      },
      {
        id: uniqueId(),
        title: 'Blogs',
        icon: IconPoint,
        href: '/blogs',
        children: [
          {
            id: uniqueId(),
            title: 'Add New Blog',
            icon: IconPoint,
            href: '/blogs/create',
          },
          {
            id: uniqueId(),
            title: 'List Blogs',
            icon: IconPoint,
            href: '/blogs/list',
          },
          {
            id: uniqueId(),
            title: 'Deleted Blogs',
            icon: IconPoint,
            href: '/blogs/deleted',
          },
        ],
      },
      {
        id: uniqueId(),
        title: 'Portfolio',
        icon: IconPoint,
        href: '/frontend-pages/portfolio',
      },
      {
        id: uniqueId(),
        title: 'Pricing',
        icon: IconPoint,
        href: '/frontend-pages/pricing',
      },
      {
        id: uniqueId(),
        title: 'Become a Seller',
        icon: IconPoint,
        href: '/frontend-pages/become-seller',
      },
      {
        id: uniqueId(),
        title: 'Policies',
        icon: IconPoint,
        href: '/frontend-pages/policies',
        children: [
          {
            id: uniqueId(),
            title: 'Privacy',
            icon: IconPoint,
            href: '/policies/privacy',
          },
          {
            id: uniqueId(),
            title: 'Return',
            icon: IconPoint,
            href: '/policies/return',
          },
          {
            id: uniqueId(),
            title: 'Refund',
            icon: IconPoint,
            href: '/policies/refund',
          },
        ],
      },
      {
        id: uniqueId(),
        title: 'Upcoming Offers',
        icon: IconPoint,
        href: '/frontend-pages/upcoming-offers',
      },
    ],
  },

  {
    navlabel: true,
    subheader: 'Main Store',
  },
  {
    id: uniqueId(),
    title: 'Orders',
    icon: IconShoppingCart,
    href: '/main-store/orders/',
    children: [
      {
        id: uniqueId(),
        title: 'List Orders',
        icon: IconPoint,
        href: '/main-store/orders/list',
      },
      {
        id: uniqueId(),
        title: 'Pending Orders',
        icon: IconPoint,
        href: '/main-store/orders/pending',
      },
      {
        id: uniqueId(),
        title: 'Received Orders',
        icon: IconPoint,
        href: '/main-store/orders/received',
      },
    ],
  },
  {
    id: uniqueId(),
    title: 'Products',
    icon: IconPackage,
    href: '/main-store/products',
    children: [
      {
        id: uniqueId(),
        title: 'Shop',
        icon: IconPoint,
        href: '/main-store/products/shop',
      },
      {
        id: uniqueId(),
        title: 'Add New Product',
        icon: IconPoint,
        href: '/main-store/products/create',
      },
      {
        id: uniqueId(),
        title: 'List Products',
        icon: IconPoint,
        href: '/main-store/products/list',
      },
      {
        id: uniqueId(),
        title: 'Deleted Products',
        icon: IconPoint,
        href: '/main-store/products/deleted',
      },
    ],
  },
  {
    id: uniqueId(),
    title: 'Categories',
    icon: IconCategory,
    href: '/main-store/categories',
    children: [
      {
        id: uniqueId(),
        title: 'Add New Category',
        icon: IconPoint,
        href: '/main-store/categories/create',
      },
      {
        id: uniqueId(),
        title: 'List Categories',
        icon: IconPoint,
        href: '/main-store/categories/list',
      },
    ],
  },
  {
    id: uniqueId(),
    title: 'Tags',
    icon: IconTags,
    href: '/main-store/tags',
    children: [
      {
        id: uniqueId(),
        title: 'Add New Tag',
        icon: IconPoint,
        href: '/main-store/tags/create',
      },
      {
        id: uniqueId(),
        title: 'List Tags',
        icon: IconPoint,
        href: '/main-store/tags/list',
      },
    ],
  },
  {
    id: uniqueId(),
    title: 'Warehouse',
    icon: IconBuildingWarehouse,
    href: '/main-store/warehouse',
    children: [
      {
        id: uniqueId(),
        title: 'Purchases',
        icon: IconPoint,
        href: '/main-store/warehouse/purchases',
        children: [
          {
            id: uniqueId(),
            title: 'Add New Purchase',
            icon: IconPoint,
            href: '/main-store/warehouse/purchases/create',
          },
          {
            id: uniqueId(),
            title: 'List Purchases',
            icon: IconPoint,
            href: '/main-store/warehouse/purchases/list',
          },
        ],
      },
      {
        id: uniqueId(),
        title: 'Inventory',
        icon: IconPoint,
        href: '/main-store/warehouse/inventory',
        children: [
          {
            id: uniqueId(),
            title: 'Add New Inventory',
            icon: IconPoint,
            href: '/main-store/warehouse/inventory/create',
          },
          {
            id: uniqueId(),
            title: 'List Inventory',
            icon: IconPoint,
            href: '/main-store/warehouse/inventory/list',
          },
        ],
      },
    ],
  },
  {
    id: uniqueId(),
    title: 'Attributes',
    icon: IconAdjustmentsHorizontal,
    href: '/main-store/attributes',
    children: [
      {
        id: uniqueId(),
        title: 'Add New Attribute',
        icon: IconPoint,
        href: '/main-store/attributes/create',
      },
      {
        id: uniqueId(),
        title: 'List Attributes',
        icon: IconPoint,
        href: '/main-store/attributes/list',
      },
    ],
  },
  {
    id: uniqueId(),
    title: 'Invoices',
    icon: IconFileInvoice,
    href: '/main-store/invoices',
    children: [
      {
        id: uniqueId(),
        title: 'Add New Invoice',
        icon: IconPoint,
        href: '/main-store/invoices/create',
      },
      {
        id: uniqueId(),
        title: 'List Invoices',
        icon: IconPoint,
        href: '/main-store/invoices/list',
      },
      {
        id: uniqueId(),
        title: 'Deleted Invoices',
        icon: IconPoint,
        href: '/main-store/invoices/deleted',
      },
    ],
  },
  {
    id: uniqueId(),
    title: 'Brands',
    icon: IconTrademark,
    href: '/main-store/brands',
    children: [
      {
        id: uniqueId(),
        title: 'Add New Brand',
        icon: IconPoint,
        href: '/main-store/brands/create',
      },
      {
        id: uniqueId(),
        title: 'List Brands',
        icon: IconPoint,
        href: '/main-store/brands/list',
      },
    ],
  },
  {
    id: uniqueId(),
    title: 'Coupons',
    icon: IconDiscount2,
    href: '/main-store/coupons',
    children: [
      {
        id: uniqueId(),
        title: 'Add New Coupon',
        icon: IconPoint,
        href: '/main-store/coupons/create',
      },
      {
        id: uniqueId(),
        title: 'List Coupons',
        icon: IconPoint,
        href: '/main-store/coupons/list',
      },
    ],
  },
  {
    id: uniqueId(),
    title: 'Reviews',
    icon: IconStars,
    href: '/main-store/reviews',
  },
  {
    id: uniqueId(),
    title: 'Settings',
    icon: IconSettings,
    href: '/main-store/settings',
  },

  {
    navlabel: true,
    subheader: 'User Management',
  },
  {
    id: uniqueId(),
    title: 'All Users',
    icon: IconUsers,
    href: '/user-manage/all-users',
    children: [
      {
        id: uniqueId(),
        title: 'Create New User',
        icon: IconPoint,
        href: '/user-manage/users/create',
      },
      {
        id: uniqueId(),
        title: 'List Users',
        icon: IconPoint,
        href: '/user-manage/users/list',
      },
      {
        id: uniqueId(),
        title: 'Deleted Users',
        icon: IconPoint,
        href: '/user-manage/users/deleted',
      },
      {
        id: uniqueId(),
        title: 'Admin Account Setting',
        icon: IconPoint,
        href: '/user-manage/users/account-settings',
      },
    ],
  },
  {
    id: uniqueId(),
    title: 'Roles',
    icon: IconCrown,
    href: '/user-manage/roles',
    children: [
      {
        id: uniqueId(),
        title: 'Add New Role',
        icon: IconPoint,
        href: '/user-manage/roles/create',
      },
      {
        id: uniqueId(),
        title: 'List Roles',
        icon: IconPoint,
        href: '/user-manage/roles/list',
      },
    ],
  },
  {
    id: uniqueId(),
    title: 'Permissions',
    icon: IconKey,
    href: '/user-manage/permissions',
    children: [
      {
        id: uniqueId(),
        title: 'Add New Permission',
        icon: IconPoint,
        href: '/user-manage/permissions/create',
      },
      {
        id: uniqueId(),
        title: 'List Permissions',
        icon: IconPoint,
        href: '/user-manage/permissions/list',
      },
    ],
  },
  {
    id: uniqueId(),
    title: 'Customers',
    icon: IconAddressBook,
    href: '/user-manage/customers',
    children: [
      {
        id: uniqueId(),
        title: 'Add New Customer',
        icon: IconPoint,
        href: '/user-manage/customers/create',
      },
      {
        id: uniqueId(),
        title: 'List Customers',
        icon: IconPoint,
        href: '/user-manage/customers/list',
      },
    ],
  },
  {
    id: uniqueId(),
    title: 'Staff',
    icon: IconIdBadge2,
    href: '/user-manage/staff',
    children: [
      {
        id: uniqueId(),
        title: 'Add New Staff',
        icon: IconPoint,
        href: '/user-manage/staff/create',
      },
      {
        id: uniqueId(),
        title: 'List Staff',
        icon: IconPoint,
        href: '/user-manage/staff/list',
      },
    ],
  },
  {
    id: uniqueId(),
    title: 'Sellers',
    icon: IconBuildingStore,
    href: '/user-manage/sellers',
    children: [
      {
        id: uniqueId(),
        title: 'Add New Seller',
        icon: IconPoint,
        href: '/user-manage/sellers/create',
      },
      {
        id: uniqueId(),
        title: 'List Sellers',
        icon: IconPoint,
        href: '/user-manage/sellers/list',
      },
    ],
  },
  {
    navlabel: true,
    subheader: 'Support',
  },

  {
    id: uniqueId(),
    title: 'Contacts',
    icon: IconPackage,
    chip: '2',
    chipColor: 'secondary',
    href: '/apps/contacts',
  },
  {
    id: uniqueId(),
    title: 'Chats',
    icon: IconMessage2,
    href: '/apps/chats',
  },
  {
    id: uniqueId(),
    title: 'Notes',
    icon: IconNotes,
    href: '/apps/notes',
  },
  {
    id: uniqueId(),
    title: 'Calendar',
    icon: IconCalendar,
    href: '/apps/calendar',
  },
  {
    id: uniqueId(),
    title: 'Email',
    icon: IconMail,
    href: '/apps/email',
  },
  {
    id: uniqueId(),
    title: 'Tickets',
    icon: IconTicket,
    href: '/apps/tickets',
  },
  {
    id: uniqueId(),
    title: 'Teamwork Processes',
    icon: IconNotebook,
    href: '/apps/teamwork-processes',
  },

  {
    navlabel: true,
    subheader: 'Systems',
  },
  {
    id: uniqueId(),
    title: 'Domains',
    icon: IconWorldMinus,
    href: '/domains/',
    children: [
      {
        id: uniqueId(),
        title: 'Create Domain',
        icon: IconPoint,
        href: '/domains/create',
      },
      {
        id: uniqueId(),
        title: 'All Domains',
        icon: IconPoint,
        href: '/domains/all',
      },
      {
        id: uniqueId(),
        title: 'Custom Domains Requests',
        icon: IconPoint,
        href: '/domains/custom-domains-requests',
      },
    ],
  },
  {
    id: uniqueId(),
    title: 'Language',
    icon: IconLanguage,
    href: '/language/',
    children: [
      {
        id: uniqueId(),
        title: 'Create Language',
        icon: IconPoint,
        href: '/language/create',
      },
      {
        id: uniqueId(),
        title: 'Manage Language',
        icon: IconPoint,
        href: '/language/manage',
      },
    ],
  },

  {
    id: uniqueId(),
    title: 'Marketing tools',
    icon: IconTarget,
    href: '/marketing-tools',
  },
  {
    id: uniqueId(),
    title: 'Payment gateways',
    icon: IconCreditCard,
    href: '/payment-gateways',
  },
  {
    id: uniqueId(),
    title: 'Shipping',
    icon: IconTruck,
    href: '/shipping/',
    children: [
      {
        id: uniqueId(),
        title: 'Companies',
        icon: IconPoint,
        href: '/shipping/companies',
      },
      {
        id: uniqueId(),
        title: 'Matrix',
        icon: IconPoint,
        href: '/shipping/matrix',
      },
    ],
  },

  {
    navlabel: true,
    subheader: 'Other',
  },
  {
    id: uniqueId(),
    title: 'Develop Mode',
    icon: IconBrandCodesandbox,
    href: '/develop-mode/',
    children: [
      {
        id: uniqueId(),
        title: 'eCommerce',
        icon: IconPoint,
        href: '/dashboards/ecommerce',
      },
      {
        id: uniqueId(),
        title: 'Products',
        icon: IconPoint,
        href: '/main-store/products',
        children: [
          {
            id: uniqueId(),
            title: 'Shop',
            icon: IconPoint,
            href: '/apps/ecommerce/shop',
          },
          {
            id: uniqueId(),
            title: 'Detail',
            icon: IconPoint,
            href: '/apps/ecommerce/detail/1',
          },
          {
            id: uniqueId(),
            title: 'List',
            icon: IconPoint,
            href: '/apps/ecommerce/eco-product-list',
          },
          {
            id: uniqueId(),
            title: 'Checkout',
            icon: IconPoint,
            href: '/apps/ecommerce/eco-checkout',
          },
          {
            id: uniqueId(),
            title: 'Add Product',
            icon: IconPoint,
            href: '/apps/ecommerce/add-product',
          },
          {
            id: uniqueId(),
            title: 'Edit Product',
            icon: IconPoint,
            href: '/apps/ecommerce/edit-product',
          },
        ],
      },
      {
        id: uniqueId(),
        title: 'Blogs',
        icon: IconPoint,
        href: '/frontend-pages/blogs',
        children: [
          {
            id: uniqueId(),
            title: 'Posts',
            icon: IconPoint,
            href: '/develop-mode/blog',
          },
          {
            id: uniqueId(),
            title: 'Details',
            icon: IconPoint,
            href: '/develop-mode/blog/detail/streaming-video-way-before-it-was-cool-go-dark-tomorrow',
          },
        ],
      },
      {
        id: uniqueId(),
        title: 'Users',
        icon: IconPoint,
        href: '/user-profile',
        children: [
          {
            id: uniqueId(),
            title: 'Profile',
            icon: IconPoint,
            href: '/user-profile',
          },
          {
            id: uniqueId(),
            title: 'Followers',
            icon: IconPoint,
            href: '/apps/followers',
          },
          {
            id: uniqueId(),
            title: 'Friends',
            icon: IconPoint,
            href: '/apps/friends',
          },
          {
            id: uniqueId(),
            title: 'Gallery',
            icon: IconPoint,
            href: '/apps/gallery',
          },
        ],
      },
      {
        id: uniqueId(),
        title: 'Widgets',
        icon: IconPoint,
        href: '/widgets/cards',
        children: [
          {
            id: uniqueId(),
            title: 'Cards',
            icon: IconPoint,
            href: '/widgets/cards',
          },
          {
            id: uniqueId(),
            title: 'Banners',
            icon: IconPoint,
            href: '/widgets/banners',
          },
          {
            id: uniqueId(),
            title: 'Charts',
            icon: IconPoint,
            href: '/widgets/charts',
          },
        ],
      },
      {
        id: uniqueId(),
        title: 'Forms',
        icon: IconPoint,
        href: '/forms/',
        children: [
          {
            id: uniqueId(),
            title: 'Form Elements',
            icon: IconApps,
            href: '/forms/form-elements/autocomplete',
            children: [
              {
                id: uniqueId(),
                title: 'Autocomplete',
                icon: IconPoint,
                href: '/forms/form-elements/autocomplete',
              },
              {
                id: uniqueId(),
                title: 'Button',
                icon: IconPoint,
                href: '/forms/form-elements/button',
              },
              {
                id: uniqueId(),
                title: 'Checkbox',
                icon: IconPoint,
                href: '/forms/form-elements/checkbox',
              },
              {
                id: uniqueId(),
                title: 'Radio',
                icon: IconPoint,
                href: '/forms/form-elements/radio',
              },
              {
                id: uniqueId(),
                title: 'Date Time',
                icon: IconPoint,
                href: '/forms/form-elements/date-time',
              },
              {
                id: uniqueId(),
                title: 'Slider',
                icon: IconPoint,
                href: '/forms/form-elements/slider',
              },
              {
                id: uniqueId(),
                title: 'Switch',
                icon: IconPoint,
                href: '/forms/form-elements/switch',
              },
            ],
          },
          {
            id: uniqueId(),
            title: 'Form Layout',
            icon: IconFileDescription,
            href: '/forms/form-layouts',
          },
          {
            id: uniqueId(),
            title: 'Form Horizontal',
            icon: IconBoxAlignBottom,
            href: '/forms/form-horizontal',
          },
          {
            id: uniqueId(),
            title: 'Form Vertical',
            icon: IconBoxAlignLeft,
            href: '/forms/form-vertical',
          },
          {
            id: uniqueId(),
            title: 'Form Custom',
            icon: IconFileDots,
            href: '/forms/form-custom',
          },
          {
            id: uniqueId(),
            title: 'Form Wizard',
            icon: IconFiles,
            href: '/forms/form-wizard',
          },
          {
            id: uniqueId(),
            title: 'Form Validation',
            icon: IconFiles,
            href: '/forms/form-validation',
          },
          {
            id: uniqueId(),
            title: 'Tiptap Editor',
            icon: IconEdit,
            href: '/forms/form-tiptap',
          },
        ],
      },
      {
        id: uniqueId(),
        title: 'Tables',
        icon: IconPoint,
        href: '/tables/',
        children: [
          {
            id: uniqueId(),
            title: 'Basic',
            icon: IconBorderAll,
            href: '/tables/basic',
          },
          {
            id: uniqueId(),
            title: 'Collapsible',
            icon: IconBorderHorizontal,
            href: '/tables/collapsible',
          },
          {
            id: uniqueId(),
            title: 'Enhanced',
            icon: IconBorderInner,
            href: '/tables/enhanced',
          },
          {
            id: uniqueId(),
            title: 'Fixed Header',
            icon: IconBorderVertical,
            href: '/tables/fixed-header',
          },
          {
            id: uniqueId(),
            title: 'Pagination',
            icon: IconBorderTop,
            href: '/tables/pagination',
          },
          {
            id: uniqueId(),
            title: 'Search',
            icon: IconBorderStyle2,
            href: '/tables/search',
          },
          {
            id: uniqueId(),
            title: 'React Table',
            icon: IconBorderStyle2,
            href: '/react-tables/basic',
            children: [
              {
                id: uniqueId(),
                title: 'Basic',
                icon: IconPoint,
                href: '/react-tables/basic',
              },
              {
                id: uniqueId(),
                title: 'Dense',
                icon: IconPoint,
                href: '/react-tables/dense',
              },
              {
                id: uniqueId(),
                title: 'Filter',
                icon: IconPoint,
                href: '/react-tables/filter',
              },
              {
                id: uniqueId(),
                title: 'Row Selection',
                icon: IconPoint,
                href: '/react-tables/row-selection',
              },
              {
                id: uniqueId(),
                title: 'Pagination',
                icon: IconPoint,
                href: '/react-tables/pagination',
              },
              {
                id: uniqueId(),
                title: 'Sorting',
                icon: IconPoint,
                href: '/react-tables/sorting',
              },
              {
                id: uniqueId(),
                title: 'Column Visibility',
                icon: IconPoint,
                href: '/react-tables/column-visiblity',
              },
              {
                id: uniqueId(),
                title: 'Editable',
                icon: IconPoint,
                href: '/react-tables/editable',
              },
              {
                id: uniqueId(),
                title: 'Expanding',
                icon: IconPoint,
                href: '/react-tables/expanding',
              },
              {
                id: uniqueId(),
                title: 'Sticky',
                icon: IconPoint,
                href: '/react-tables/sticky',
              },
              {
                id: uniqueId(),
                title: 'Empty',
                icon: IconPoint,
                href: '/react-tables/empty',
              },
              {
                id: uniqueId(),
                title: 'Drag & Drop',
                icon: IconPoint,
                href: '/react-tables/drag-drop',
              },
            ],
          },
        ],
      },
      {
        id: uniqueId(),
        title: 'Mui Charts',
        icon: IconPoint,
        href: '/muicharts/',
        children: [
          {
            id: uniqueId(),
            title: 'BarCharts',
            icon: IconChartHistogram,
            href: '/muicharts/barcharts',
          },
          {
            id: uniqueId(),
            title: 'LineCharts',
            icon: IconChartLine,
            href: '/muicharts/linecharts/line',
            children: [
              {
                id: uniqueId(),
                title: 'Lines',
                icon: IconPoint,
                href: '/muicharts/linecharts/line',
              },
              {
                id: uniqueId(),
                title: 'Area',
                icon: IconPoint,
                href: '/muicharts/linecharts/area',
              },
            ],
          },
          {
            id: uniqueId(),
            title: 'PieCharts',
            icon: IconChartPie2,
            href: '/muicharts/piecharts',
          },
          {
            id: uniqueId(),
            title: 'ScatterCharts',
            icon: IconChartScatter,
            href: '/muicharts/scattercharts',
          },
          {
            id: uniqueId(),
            title: 'SparklineCharts',
            icon: IconChartPpf,
            href: '/muicharts/sparklinecharts',
          },
          {
            id: uniqueId(),
            title: 'GaugeCharts',
            icon: IconChartArcs3,
            href: '/muicharts/gaugecharts',
          },
        ],
      },
      {
        id: uniqueId(),
        title: 'SimpleTreeView',
        icon: IconPoint,
        href: '/mui-trees/simpletree/simpletree-items',
        children: [
          {
            id: uniqueId(),
            title: 'Items',
            icon: IconPoint,
            href: '/mui-trees/simpletree/simpletree-items',
          },
          {
            id: uniqueId(),
            title: 'Selection',
            icon: IconPoint,
            href: '/mui-trees/simpletree/simpletree-selection',
          },
          {
            id: uniqueId(),
            title: 'Expansion',
            icon: IconPoint,
            href: '/mui-trees/simpletree/simpletree-expansion',
          },
          {
            id: uniqueId(),
            title: 'Customization',
            icon: IconPoint,
            href: '/mui-trees/simpletree/simpletree-customization',
          },
          {
            id: uniqueId(),
            title: 'Focus',
            icon: IconPoint,
            href: '/mui-trees/simpletree/simpletree-focus',
          },
        ],
      },
      {
        id: uniqueId(),
        title: 'Ui Components',
        icon: IconPoint,
        href: '/ui-components/',
        children: [
          {
            id: uniqueId(),
            title: 'Alert',
            icon: IconPoint,
            href: '/ui-components/alert',
          },
          {
            id: uniqueId(),
            title: 'Accordion',
            icon: IconPoint,
            href: '/ui-components/accordion',
          },
          {
            id: uniqueId(),
            title: 'Avatar',
            icon: IconPoint,
            href: '/ui-components/avatar',
          },
          {
            id: uniqueId(),
            title: 'Chip',
            icon: IconPoint,
            href: '/ui-components/chip',
          },
          {
            id: uniqueId(),
            title: 'Dialog',
            icon: IconPoint,
            href: '/ui-components/dialog',
          },
          {
            id: uniqueId(),
            title: 'List',
            icon: IconPoint,
            href: '/ui-components/list',
          },
          {
            id: uniqueId(),
            title: 'Popover',
            icon: IconPoint,
            href: '/ui-components/popover',
          },
          {
            id: uniqueId(),
            title: 'Rating',
            icon: IconPoint,
            href: '/ui-components/rating',
          },
          {
            id: uniqueId(),
            title: 'Tabs',
            icon: IconPoint,
            href: '/ui-components/tabs',
          },
          {
            id: uniqueId(),
            title: 'Tooltip',
            icon: IconPoint,
            href: '/ui-components/tooltip',
          },
          {
            id: uniqueId(),
            title: 'Transfer List',
            icon: IconPoint,
            href: '/ui-components/transfer-list',
          },
          {
            id: uniqueId(),
            title: 'Typography',
            icon: IconPoint,
            href: '/ui-components/typography',
          },
        ],
      },
      {
        id: uniqueId(),
        title: 'Charts',
        icon: IconPoint,
        href: '/charts/',
        children: [
          {
            id: uniqueId(),
            title: 'Line',
            icon: IconChartLine,
            href: '/charts/line-chart',
          },
          {
            id: uniqueId(),
            title: 'Gredient',
            icon: IconChartArcs,
            href: '/charts/gredient-chart',
          },
          {
            id: uniqueId(),
            title: 'Area',
            icon: IconChartArea,
            href: '/charts/area-chart',
          },
          {
            id: uniqueId(),
            title: 'Candlestick',
            icon: IconChartCandle,
            href: '/charts/candlestick-chart',
          },
          {
            id: uniqueId(),
            title: 'Column',
            icon: IconChartDots,
            href: '/charts/column-chart',
          },
          {
            id: uniqueId(),
            title: 'Doughtnut & Pie',
            icon: IconChartDonut3,
            href: '/charts/doughnut-pie-chart',
          },
          {
            id: uniqueId(),
            title: 'RadialBar & Radar',
            icon: IconChartRadar,
            href: '/charts/radialbar-chart',
          },
        ],
      },
      {
        id: uniqueId(),
        title: 'Auth',
        icon: IconPoint,
        href: '/auth/',
        children: [
          {
            id: uniqueId(),
            title: 'Login',
            icon: IconLogin,
            href: '/auth/login',
            children: [
              {
                id: uniqueId(),
                title: 'Side Login',
                icon: IconPoint,
                href: '/auth/login',
              },
              {
                id: uniqueId(),
                title: 'Boxed Login',
                icon: IconPoint,
                href: '/auth/login2',
              },
            ],
          },
          {
            id: uniqueId(),
            title: 'Register',
            icon: IconUserPlus,
            href: '/auth/register',
            children: [
              {
                id: uniqueId(),
                title: 'Side Register',
                icon: IconPoint,
                href: '/auth/register',
              },
              {
                id: uniqueId(),
                title: 'Boxed Register',
                icon: IconPoint,
                href: '/auth/register2',
              },
            ],
          },
          {
            id: uniqueId(),
            title: 'Forgot Password',
            icon: IconRotate,
            href: '/auth/forgot-password',
            children: [
              {
                id: uniqueId(),
                title: 'Side Forgot Password',
                icon: IconPoint,
                href: '/auth/forgot-password',
              },
              {
                id: uniqueId(),
                title: 'Boxed Forgot Password',
                icon: IconPoint,
                href: '/auth/forgot-password2',
              },
            ],
          },

          {
            id: uniqueId(),
            title: 'Two Steps',
            icon: IconZoomCode,
            href: '/auth/two-steps',
            children: [
              {
                id: uniqueId(),
                title: 'Side Two Steps',
                icon: IconPoint,
                href: '/auth/two-steps',
              },
              {
                id: uniqueId(),
                title: 'Boxed Two Steps',
                icon: IconPoint,
                href: '/auth/two-steps2',
              },
            ],
          },
          {
            id: uniqueId(),
            title: 'Error',
            icon: IconAlertCircle,
            href: '/400',
          },
          {
            id: uniqueId(),
            title: 'Maintenance',
            icon: IconSettings,
            href: '/auth/maintenance',
          },
        ],
      },
      {
        id: uniqueId(),
        title: 'Menu Level',
        icon: IconPoint,
        href: '/menulevel/',
        children: [
          {
            id: uniqueId(),
            title: 'Level 1',
            icon: IconPoint,
            href: '/l1',
          },
          {
            id: uniqueId(),
            title: 'Level 1.1',
            icon: IconPoint,
            href: '/l1.1',
            children: [
              {
                id: uniqueId(),
                title: 'Level 2',
                icon: IconPoint,
                href: '/l2',
              },
              {
                id: uniqueId(),
                title: 'Level 2.1',
                icon: IconPoint,
                href: '/l2.1',
                children: [
                  {
                    id: uniqueId(),
                    title: 'Level 3',
                    icon: IconPoint,
                    href: '/l3',
                  },
                  {
                    id: uniqueId(),
                    title: 'Level 3.1',
                    icon: IconPoint,
                    href: '/l3.1',
                  },
                ],
              },
            ],
          },
        ],
      },
      {
        id: uniqueId(),
        title: 'Disabled',
        icon: IconPoint,
        href: '/',
        disabled: true,
      },
      {
        id: uniqueId(),
        title: 'SubCaption',
        subtitle: 'This is the sutitle',
        icon: IconPoint,
        href: '/',
      },

      {
        id: uniqueId(),
        title: 'Chip',
        icon: IconPoint,
        href: '/',
        chip: '9',
        chipColor: 'primary',
      },
      {
        id: uniqueId(),
        title: 'Outlined',
        icon: IconPoint,
        href: '/',
        chip: 'outline',
        variant: 'outlined',
        chipColor: 'primary',
      },
      {
        id: uniqueId(),
        title: 'External Link',
        external: true,
        icon: IconPoint,
        href: 'https://google.com',
      },
    ],
  },
];

export default Menuitems;
